import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import "./globals.css";
import ErrorBoundary from "@/components/ui/ErrorBoundary";

const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--font-mono",
});

export const metadata: Metadata = {
  title: "Nadir AMMI SAID - Full-Stack Developer",
  description:
    "CV interactif sous forme de terminal - Développeur Full-Stack spécialisé en TypeScript, React, Node.js",
  keywords:
    "développeur, full-stack, TypeScript, React, Node.js, CV, portfolio, terminal",
  authors: [{ name: "Nadir AMMI SAID" }],
  creator: "Nadir AMMI SAID",
  openGraph: {
    title: "Nadir AMMI SAID - Développeur Full-Stack",
    description: "CV interactif sous forme de terminal",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "Nadir AMMI SAID - Développeur Full-Stack",
    description: "CV interactif sous forme de terminal",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr">
      <body className={`${firaCode.variable} font-mono antialiased`}>
        <ErrorBoundary>{children}</ErrorBoundary>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
